packages:
  - 'packages/*'
  - 'playground/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  rs-module-lexer: false
  vue-demi: false

minimumReleaseAgeExclude:
  - '@lobehub/ui@5.47.1'
  - ultracite@7.12.0

patchedDependencies:
  '@lobehub/docs-kit@5.27.3': 'patches/@lobehub__docs-kit@5.27.3.patch'
