packages:
  - 'docs'
  - 'packages/*'
  - 'playground/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  rs-module-lexer: false
  vue-demi: false

minimumReleaseAgeExclude:
  - '@lobehub/ui@5.47.1'
  - ultracite@7.12.0

